unity_bridge:
  # How many time the robot can replan due to environment changes
  replan_attempt: 5
  # How long to wait before replanning occur
  replan_delay: 1.0
  # How many instance of planner to be run in parallel per attempt
  parallel_planners: 4
  # How many seconds before timing out the planner
  planning_timeout: 30
  # Mainpaths Pipeline ID
  main_planner_pipeline: ompl
  # ID of the planner used for main paths (prepick, preplace, home). Valid only for ompl
  main_planner_id: PRM
  # Sidepaths Pipeline ID
  side_planner_pipeline: ompl
  # ID of the planner used for side paths (pick, place, postpick, postplace). Valid only for ompl
  side_planner_id: PRM
  # Dynamic object avoidance is only available if cached path and profiling is turned off
  # Use warehouse to store previous valid path? Is ignored if profiling is true.
  use_cached_path: false
  # Generate profiling data? If true, cached path is ignored.
  profiling: false
  # Take energy data from the robot hardware or use Unity's; Only applicable to profiled run
  use_energy_estimation: false
  # Draw orientation arrow in rviz at prepick, pick, preplace, place location?
  generate_pick_place_marker: false
