controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
  - name: fake_robot_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger_joint
initial:  # Define initial robot poses per group
  - group: robot_arm
    pose: home
  - group: robot_gripper
    pose: gripper_open