# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robot_arm_controller
    - robot_gripper_controller

  robot_arm_controller:
    type: FollowJointTrajectory
    joints:
      - robot_shoulder_pan_joint
      - robot_shoulder_lift_joint
      - robot_elbow_joint
      - robot_wrist_1_joint
      - robot_wrist_2_joint
      - robot_wrist_3_joint
  robot_gripper_controller:
    type: GripperCommand
    joints:
      - gripper_finger_joint
    action_ns: gripper_cmd
    default: true