# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    robot_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_arm_controller:
  ros__parameters:
    joints:
      - robot_shoulder_pan_joint
      - robot_shoulder_lift_joint
      - robot_elbow_joint
      - robot_wrist_1_joint
      - robot_wrist_2_joint
      - robot_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
robot_gripper_controller:
  ros__parameters:
    joint: gripper_finger_joint