# Settings for ros_control hardware interface
ur_hardware_interface:
  joints:
    - arm_shoulder_pan_joint
    - arm_shoulder_lift_joint
    - arm_elbow_joint
    - arm_wrist_1_joint
    - arm_wrist_2_joint
    - arm_wrist_3_joint
# Settings for ros_control control loop
hardware_control_loop:
  loop_hz: 500
# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: 500

# Taken from https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/config/ur10e_controllers.yaml
robot_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_shoulder_pan_joint
    - arm_shoulder_lift_joint
    - arm_elbow_joint
    - arm_wrist_1_joint
    - arm_wrist_2_joint
    - arm_wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    shoulder_pan_joint:
      trajectory: 0.2
      goal: 0.1
    shoulder_lift_joint:
      trajectory: 0.2
      goal: 0.1
    elbow_joint:
      trajectory: 0.2
      goal: 0.1
    wrist_1_joint:
      trajectory: 0.2
      goal: 0.1
    wrist_2_joint:
      trajectory: 0.2
      goal: 0.1
    wrist_3_joint:
      trajectory: 0.2
      goal: 0.1
  state_publish_rate: 500
  stop_trajectory_duration: 0.5
  action_monitor_rate: 20