# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_shoulder_pan_joint
    - arm_shoulder_lift_joint
    - arm_elbow_joint
    - arm_wrist_1_joint
    - arm_wrist_2_joint
    - arm_wrist_3_joint
    - gripper_finger_joint
  sim_control_mode: 0
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.01
# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: 50

robot_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_shoulder_pan_joint
    - arm_shoulder_lift_joint
    - arm_elbow_joint
    - arm_wrist_1_joint
    - arm_wrist_2_joint
    - arm_wrist_3_joint
  gains:
    arm_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
robot_gripper_controller:
  type: position_controllers/GripperActionController
  joint: gripper_finger_joint